# https://lmno.pk/post/configuring-external-dns-technitium/
provider:
  name: rfc2136

extraArgs:
  - --rfc2136-host=10.40.0.51
  - --rfc2136-port=53
  - --rfc2136-zone=gruppe1.lan
  - --rfc2136-tsig-secret-alg=hmac-sha256
  - --rfc2136-tsig-keyname=external-dns
  - --rfc2136-tsig-axfr

env:
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: tsig-key
        key: key
