---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-test
  template:
    metadata:
      labels:
        app: echo-test
    spec:
      containers:
      - name: echo-test
        image: fdeantoni/echo-server
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-test
spec:
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    app: echo-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-test
  annotations:
    cert-manager.io/cluster-issuer: acme-issuer
    traefik.ingress.kubernetes.io/router.middlewares: traefik-internal-whitelist@kubernetescrd # internal only. comment out for external access
spec:
  ingressClassName: traefik
  rules:
  - host: echo-test.gruppe1.lan # change me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-test
            port:
              number: 9000
